### ISSUE TITLE
[bug solution] Error 422 solution

### ISSUE THREAD

**Issue by ufolux** [CarGuo/GSYGithubAppFlutter#263]
When I try to login, the github api throw a exception code 422 and I find [this answer](https://stackoverflow.com/questions/41168821/basic-authentication-in-android-using-volley-for-github-getting-error-code-422) can be a solution to this problem.

**Comment by ufolux** [comment]
I create a pull request #264, please check and merge it.

**Comment by qfdk** [comment]
遇到同样的问题。
#264 解决了 此问题，希望原作者merge

**Comment by CarGuo** [comment]
merge

**Comment by CarGuo** [comment]
@qfdk 其实并没有解决，因为get方法调用授权接口并没有返回token，也并没有存在本地，请求时用的是由账号密码组合生成的授权码，这时候按照程序逻辑，每次启动会因为读取不到本地token，每次都进去登录界面。

**Comment by CarGuo** [comment]
@ufolux 

Because the Get method call authorization interface does not return token and does not save token locally.

the request is made with the authorization code generated by the combination of account and passwords. 

At this time, according to the program logic, every time start app will enter the login page because the local token can not be read.
